// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxRYFoHxHE6Xb9v80YM8lO1jv9u-m-Mg0',
    appId: '1:369529305644:web:807f513b7b3b08f74caf89',
    messagingSenderId: '369529305644',
    projectId: 'hinoki-d9d87',
    authDomain: 'hinoki-d9d87.firebaseapp.com',
    storageBucket: 'hinoki-d9d87.firebasestorage.app',
    measurementId: 'G-GPDJM5LCMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74lfjPTKKBLAK8eV6GG5XFWVhuMmDSuc',
    appId: '1:369529305644:android:1a7f7b11c038a8454caf89',
    messagingSenderId: '369529305644',
    projectId: 'hinoki-d9d87',
    storageBucket: 'hinoki-d9d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeTcXY3xOXA6wth2z7qfoiryrm8YIefhk',
    appId: '1:369529305644:ios:7a94d6120c6408fa4caf89',
    messagingSenderId: '369529305644',
    projectId: 'hinoki-d9d87',
    storageBucket: 'hinoki-d9d87.firebasestorage.app',
    iosBundleId: 'com.example.hinokifix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeTcXY3xOXA6wth2z7qfoiryrm8YIefhk',
    appId: '1:369529305644:ios:7a94d6120c6408fa4caf89',
    messagingSenderId: '369529305644',
    projectId: 'hinoki-d9d87',
    storageBucket: 'hinoki-d9d87.firebasestorage.app',
    iosBundleId: 'com.example.hinokifix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxRYFoHxHE6Xb9v80YM8lO1jv9u-m-Mg0',
    appId: '1:369529305644:web:5f5cbf884d9b82424caf89',
    messagingSenderId: '369529305644',
    projectId: 'hinoki-d9d87',
    authDomain: 'hinoki-d9d87.firebaseapp.com',
    storageBucket: 'hinoki-d9d87.firebasestorage.app',
    measurementId: 'G-D90MJP41L4',
  );
}
